[tool.poetry]
name = "compmec-nurbs"
version = "0.2.1"
description = ""
authors = ["Carlos Adir <carlos.adir@gmail.com>"]
packages = [{ include = "nurbs", from = "src/compmec" }]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
